name: docs-preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    paths:
      - 'docs/site/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.deployment_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "::set-output name=deployment_url::$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
  comment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR with Deployment URL
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const deployment_url = '${{ needs.deploy.outputs.url }}';
            const pr_number = context.payload.pull_request.number;
            const repository = context.repo.repo;
            const owner = context.repo.owner;
            github.rest.issues.createComment({
              owner: owner,
              repo: repository,
              issue_number: pr_number,
              body: `Docs preview complete 🚀 see it here: ${deployment_url}`
            });