name: Deploy Docusaurus Site to Preview Environment

on:
  pull_request:
    branches:
      - main
    paths:
        - 'docs/site/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        working-directory: ./docs/site

      - name: Build Docusaurus Site
        run: pnpm run build
        working-directory: ./docs/site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site/build
